---
app_name: sre-hello-world

app_repo_url: https://github.com/muxx/sre-hello-world.git
app_git_ref: master
app_root: /opt/sre-hello-world

php_service_name: php
php_container_port: 9000

server_name: "_"

postgres_version: 15
postgres_db: sre
postgres_user: sre
postgres_host: host.docker.internal
postgres_port: 5432

postgres_max_connections: 100
postgres_shared_buffers_mb: "{{ (ansible_memtotal_mb * 0.25) | int }}"
postgres_effective_cache_size_mb: "{{ (ansible_memtotal_mb * 0.70) | int }}"
postgres_work_mem_mb: 4
postgres_maintenance_work_mem_mb: "{{ (ansible_memtotal_mb * 0.10) | int }}"