---
- name: Create application directory
  ansible.builtin.file:
    path: "{{ app_root }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy application
  ansible.builtin.import_tasks: deploy.yml